kind: pipeline
name: default

# Pipeline for putting cloudformation files into S3 for nested stacks
steps:
  - name: upload
    image: plugins/s3
    settings:
      bucket: craft-cf-bucket
      region: us-east-2
      access_key:
        from_secret: AWS-Key
      secret_key:
        from_secret: AWS-Secret
      source: templates/**/*
      target: /

  - name: upload-sheeta
    image: plugins/s3
    settings:
      bucket: sheeta-cfn-bucket
      region: us-east-2
      access_key:
        from_secret: new_aws_key
      secret_key:
        from_secret: new_aws_secret
      source: templates/**/*
      target: /${DRONE_COMMIT_SHA}/


