AWSTemplateFormatVersion: 2010-09-09
Description: A bucket to hold CloudFormation from Drone

Parameters:
  BucketName:
    Description: Name of CF bucket
    Type: String

  # TODO::Inherit
  OwnerTag:
    Description: Value for the 'Owner' tag
    Type: String
  ProjectTag:
    Description: Value for the 'Project' tag
    Type: String
  EnvironmentTag:
    Description: Value for the 'Environment' tag
    Type: String

Resources:
  CloudFormationBucket:
    Type: AWS::S3::Bucket
    Properties:
      # AccessControl: BucketOwnerFullControl
      BucketName:
        Ref: BucketName
      VersioningConfiguration:
        Status: "Suspended"
      Tags:
        - Key: Project
          Value:
            Ref: ProjectTag
        - Key: Owner
          Value:
            Ref: OwnerTag
        - Key: Environment
          Value:
            Ref: EnvironmentTag
