AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the MGP-Build worker
Parameters:
  AMIID:
    Description: The AMI for this instance
    Type: AWS::EC2::Image::Id
    Default: ami-0cd3dfa4e37921605

  BaseVPCStackName:
    Description: The name of the base VPC for network imports
    Type: String
    Default: craft-dev

  JenkinsPublicKey:
    Description: The RSA id key for the Jenkins master
    Type: String
    Default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCcSImBhdRvn5J9QnPTtiRQJ1CDLvzSOQA1pCRjSt3Rm6bKVg7V+op3HchvACU92UsrLqRPS8Vmz1e/7sfj2gThftWSsvTKrrVNRT7ccxxpoQBVBL6J/5ridSsO957NTArLJnTnJfDDXmyEILK1B1mUz3p6X7uWOzXd9Bkpi/eh8fnu8UoK6eWLd+EJwQkt37Rf9ILatjuQWNUQYQXLmgz+5hqXiDjXXwmUwQq3B+vUidFW1WqtUiRIcOcg9k3o2w5WfMvctja2TmC0qCqUEhOydeFQ2Gv1gdS5wP0+JUFsHq4JLg40yYJmRxv9idfGEaMum/7WW7Nhps4opnAdgZ9tP9GIH76HS21Q4tM6wSJIqrU8ODufyblaNVw8N8PNMKKThgAuPXGFa7P/4KDgS6mH6kEq7tgFpuiVXF8fMwoNt9QJImbQe8E1voQmjSzDwuRR7yvPsOMMUxQHdJ0qfXin0tFDQf9UtYICYWafv1QQ7qEh+qx9zN8grgLqP2iIjTmd4ps65q/ot752/DoPdjIqttNrsxxikwTOo3FwD6vHgbT+YkV58TsNoMlfNf5a7iS+QeYtojToR3wphFpBjuxIw3GCGFCguK+ZiqvfMG8et6x8LstecJBTcBiIYINz2qylSSXHH0xgkqE8iPUpSnJu5+T/y/tMKkBiJa1rhvJ0BQ== ian.cullinane@gmail.com

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
    ConstraintDescription: must be a valid EC2 instance type.

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIID
      KeyName: cert-key-e2
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - sg-0ad922278c408cad0 # TODO::Placeholder until we have a build base stack for roles and sg
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: ${BaseVPCStackName}-PublicSubnetId1
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash
          yum update -y aws-cfn-bootstrap # good practice - always do this.
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --configsets builder --region ${AWS::Region}
          yum -y remove java 
          yum -y update
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-jenkins

    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          builder:
            - "configure_cfn"
            - "configure_mgp_build_users"
            - "install_jre"
        install_jre:
          commands:
            rm_java_7:
              command: "yum remove java"
              ignoreErrors: "true"
          packages:
            yum:
              java-1.8.0-openjdk: []
        configure_mgp_build_users:
          groups:
            build: {}
            docker: {}
          users:
            jenkins:
              groups:
                - "build"
                - "docker"
              homeDir: "/tmp/jenkins"
        configure_cfn:
          files:
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2Instance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --configsets builder --region ${AWS::Region}
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                verbose=true
                interval=1
              mode: "000400"
              owner: root
              group: root
          services:
            sysvinit:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - "/etc/cfn/cfn-hup.conf"
                  - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance

  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt
      - EC2Instance
      - AvailabilityZone
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt
      - EC2Instance
      - PublicIp
