AWSTemplateFormatVersion: "2010-09-09"
Description: Builds a NAT and associated routes to support a private networking layer
Parameters:
  VpcId:
    Description: The VPC for the route table
    Type: String

  SubnetID:
    Type: String
    Description:
      SubnetId of an existing Public facing subnet in your Virtual Private
      Cloud (VPC)

  RtbID:
    Description: The route table to attach to
    Type: String

  GatewayID:
    Description: ID for the igw on the environment
    Type: String

Resources:
  NatGatewayEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-00d1f8201864cc10c
      InstanceType: t2.micro
      NetworkInterfaces:
        - GroupSet:
            - !Ref NatSG
          AssociatePublicIpAddress: true
          DeviceIndex: "0"
          DeleteOnTermination: true
          SubnetId: !Ref SubnetID
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-nat

  NatSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: NatInstanceSG #required
      # SecurityGroupEgress:
      #   - Egress
      # SecurityGroupIngress:
      #   - Ingress
      VpcId: !Ref VpcId

  PrivateRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-pvt-rtb

  NatRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      InstanceId: !Ref NatInstance

  PrivateSubnet1RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: SubnetID
