AWSTemplateFormatVersion: "2010-09-09"
Description: Builds a NAT and associated routes to support a private networking layer
Parameters:
  VpcId:
    Description: The VPC for the route table
    Type: String

  SubnetID:
    Type: String
    Description:
      SubnetId of an existing Public facing subnet in your Virtual Private
      Cloud (VPC)
  RtbID:
    Description: The route table to attach to
    Type: String

  GatewayID:
    Description: ID for the igw on the environment
    Type: String

Resources:
  NatGatewayEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - NatGatewayEip
          - AllocationId
      SubnetId:
        Ref: SubnetID

  PrivateRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VpcId

  NatRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnet1RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: SubnetID
