AWSTemplateFormatVersion: 2010-09-09
Description: Subnet
Parameters:
  IsPublic:
    Description: Whether or not to build public subnets
    Type: String
    AllowedValues: ["Yes", "No"]
    Default: "No"

  GatewayID:
    Description: Whether or not to build public subnets
    Type: String
    Default: ""

  CIDRMap:
    Description: List of cidrs to pass in
    Type: CommaDelimitedList

  PublicRouteTable:
    Description: The route table containing the 0.0.0.0/0 route association
    Type: String

  VpcID:
    Description: The VPC ID
    Type: String

  NumberOfAZs:
    Type: String
    AllowedValues:
      - "1"
      - "2"
      - "3"
    Default: "2"
    Description: How many Availability Zones do you wish to utilize?

  CFBucketName:
    Description: The name of the cloudformation bucket for the account
    Type: String
    Default: craft-cf-bucket

Conditions:
  IsPublic: !Equals [!Ref IsPublic, "Yes"]
  IsPrivate: !Equals [!Ref IsPublic, "No"]

Resources:
  # Depending on the type of attachemnets makes it public or private

  # subnets
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VpcID
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Select [0, !Ref CIDRMap]
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-subnet
        - "Fn::If":
            - IsPublic
            - Key: network
              Value: public
            - !Ref AWS::NoValue

  RouteAssoc1Public:
    Type: AWS::CloudFormation::Stack # required
    Condition: IsPublic
    Properties:
      Parameters:
        SubnetID: !Ref Subnet1
        RtbID: !Ref PublicRouteTable
      TemplateURL: !Sub https://${CFBucketName}.s3.us-east-2.amazonaws.com/templates/vpc/table.yaml
      TimeoutInMinutes: 10 # not required

  RouteAssoc1Private:
    Type: AWS::CloudFormation::Stack # required
    Condition: IsPrivate
    Properties:
      Parameters:
        VocId: !Ref VpcID
        SubnetID: !Ref Subnet1
        RtbID: !Ref PublicRouteTable
        GatewayID: !Ref GatewayID
      TemplateURL: !Sub https://${CFBucketName}.s3.us-east-2.amazonaws.com/templates/vpc/nat.yaml
      TimeoutInMinutes: 10 # not required

Outputs:
  PublicSubnetId1:
    Condition: IsPublic
    Description: Public Subnet ID List
    Value: !Ref Subnet1
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnetId1"
