AWSTemplateFormatVersion: 2010-09-09
Description: The route associations for a subnet

Parameters:
  SubnetID:
    Description: Requesting subnet
    Type: String

  RtbID:
    Description: The route table to associate
    Type: String

Resources:
  # Despite their names, subnets are only "public" or "private" based on the definitions of their associated routing tables.

  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetID
      RouteTableId: !Ref RtbID
# Outputs:
