AWSTemplateFormatVersion: 2010-09-09
Description: For hooking a worker in the base vpc
# Metadata:

Parameters:
  AMIId:
    Description: AMI ID to use
    Type: AWS::EC2::Image::Id
    Default: ami-0e30f3d8cbc900ff4
  # EnvBaseStackName:
  #   Description: Required for calls to ImportValue
  #   Type: String
  BaseEnvStackName:
    Description: Required for calls to ImportValue
    Type: String

  # Pass the roles actions in config, not IaC
  InstanceType:
    Description: Size of root volumes
    Type: String
    Default: "t2.micro"
  InstanceRoleActions:
    Description: The comma separated list of actions for the instance iam role policy
    Type: CommaDelimitedList
    Default: "sts:AssumeRole,autoscaling:DescribeAutoScalingInstances,autoscaling:DescribeAutoScalingGroups,route53:ListHostedZonesByName,route53:ChangeResourceRecordSets,ec2:DescribeInstances,ecr:*"
  RootVolumeSize:
    Description: Size of root volumes
    Type: String
    Default: "8"

Resources:
  ClusterBaseIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName:
            Fn::Sub: ${AWS::StackName}-cluster-policy
          PolicyDocument:
            Statement:
              Resource: "*"
              Action:
                Ref: InstanceRoleActions
              Effect: Allow

  PublicAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    # Condition: PublicIPAs
    Properties:
      LaunchConfigurationName:
        Ref: LaunchConfig
      AvailabilityZones:
        - Fn::ImportValue:
            Fn::Sub: ${BaseEnvStackName}-AZ-1
      VPCZoneIdentifier:
        - Fn::ImportValue:
            Fn::Sub: ${BaseEnvStackName}-PublicSubnetId1
      TerminationPolicies:
        - OldestInstance
      MinSize: "0"
      MaxSize: "100"
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-pool
          PropagateAtLaunch: true

  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
        Ref: AMIId
      AssociatePublicIpAddress: true
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize:
              Ref: RootVolumeSize
            VolumeType: gp2
        - DeviceName: /dev/xvdb
          VirtualName: ephemeral0
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile:
        Ref: WorkerRoleProfile
      # KeyName:
      #   Fn::ImportValue:
      #     Fn::Sub: ${ClusterBaseStackName}-KMSKeyName
      # SecurityGroups:
      #   - Fn::ImportValue:
      #       Fn::Sub: ${ClusterBaseStackName}-ClusterSGId

  WorkerIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName:
            Fn::Sub: ${AWS::StackName}-OS-policy
          PolicyDocument:
            Statement:
              Resource: "*"
              Action:
                Ref: InstanceRoleActions
              Effect: Allow

  WorkerRoleProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: WorkerIamRole
